# Generated by Django 6.0.5 on 2026-07-28 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento_tentativa', models.DateField()),
                ('hora_inicio_tentativa', models.TimeField()),
                ('hora_fin_tentativa', models.TimeField()),
                ('numero_invitados', models.PositiveIntegerField()),
                ('incluye_catering', models.BooleanField(default=False)),
                ('incluye_audiovisuales', models.BooleanField(default=False)),
                ('precio_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('comentario_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='EquipoAudiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PROYECTOR', 'Proyector'), ('SONIDO', 'Sistema de sonido'), ('ILUMINACION', 'Iluminación'), ('MICROFONO', 'Micrófono'), ('PANTALLA', 'Pantalla')], max_length=15)),
                ('cantidad_total', models.PositiveIntegerField(help_text='Unidades totales disponibles en inventario')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo Audiovisual',
                'verbose_name_plural': 'Equipos Audiovisuales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('especialidad', models.CharField(help_text='Ej: comida gourmet, bocaditos, bar', max_length=150)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor de Catering',
                'verbose_name_plural': 'Proveedores de Catering',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de invitados')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.equipoaudiovisual')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_montaje_inicio', models.DateTimeField()),
                ('fecha_evento_inicio', models.DateTimeField()),
                ('fecha_evento_fin', models.DateTimeField()),
                ('fecha_desmontaje_fin', models.DateTimeField()),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('EN_MONTAJE', 'En montaje'), ('EN_CURSO', 'En curso'), ('EN_DESMONTAJE', 'En desmontaje'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cotizacion_origen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evento', to='eventos.cotizacion')),
                ('equipos', models.ManyToManyField(blank=True, related_name='eventos', through='eventos.AsignacionEquipo', to='eventos.equipoaudiovisual')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_evento_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DisposicionSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_json', models.JSONField(blank=True, default=list)),
                ('fecha_ultima_edicion', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposicion', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Disposición de Salón',
                'verbose_name_plural': 'Disposiciones de Salón',
            },
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
        migrations.CreateModel(
            name='AsignacionCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(help_text='Ej: comida principal, postres, bar', max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.proveedorcatering')),
            ],
            options={
                'verbose_name': 'Asignación de Catering',
                'verbose_name_plural': 'Asignaciones de Catering',
                'unique_together': {('evento', 'proveedor', 'tipo_servicio')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='proveedores_catering',
            field=models.ManyToManyField(blank=True, related_name='eventos', through='eventos.AsignacionCatering', to='eventos.proveedorcatering'),
        ),
        migrations.AddField(
            model_name='evento',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.salon'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='salon_solicitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='eventos.salon'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador de Eventos')], max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='coordinador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'COORDINADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to='eventos.usuario'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='eventos.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionequipo',
            unique_together={('evento', 'equipo')},
        ),
    ]
