# Generated by Django 6.0.7 on 2026-07-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdf/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='salones/'),
        ),
    ]
