# Generated by Django 6.0.5 on 2026-07-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_factura_pdf_salon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='precio_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proveedor_catering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='eventos.proveedorcatering'),
        ),
        migrations.CreateModel(
            name='CotizacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_seleccionados', to='eventos.cotizacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.equipoaudiovisual')),
            ],
            options={
                'verbose_name': 'Equipo Deseado en Cotización',
                'verbose_name_plural': 'Equipos Deseados en Cotizaciones',
                'unique_together': {('cotizacion', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='equipos_deseados',
            field=models.ManyToManyField(blank=True, related_name='cotizaciones', through='eventos.CotizacionEquipo', to='eventos.equipoaudiovisual'),
        ),
    ]
