# Generated by Django 6.0.5 on 2026-07-29 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_cotizacion_precio_sugerido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='proveedor_catering',
        ),
        migrations.CreateModel(
            name='CotizacionCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_seleccionado', to='eventos.cotizacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.proveedorcatering')),
            ],
            options={
                'verbose_name': 'Proveedor de Catering en Cotización',
                'verbose_name_plural': 'Proveedores de Catering en Cotizaciones',
                'unique_together': {('cotizacion', 'proveedor')},
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proveedores_catering',
            field=models.ManyToManyField(blank=True, related_name='cotizaciones', through='eventos.CotizacionCatering', to='eventos.proveedorcatering'),
        ),
    ]
